import { Component, OnInit } from '@angular/core';
import { LanguageService, AppLanguages } from 'src/app/service/language/language.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {

  powerPoints = 
    {
      "results": [
        {
          "projectId": 21041,
          "projectName": "The Persian Gulf Is A Mediterranean Sea",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "../../../assets/image/english-draft.png",
          "createDate": "2020-01-15T18:10:48.96",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": true,
          "lockedTime": "2020-01-15T14:40:08.253",
          "lockedByEmail": "abe@abe.com",
          "lockedByPersonId": 9970,
          "viddlerVideoId": "cbe09119",
          "mainVideoFileDuration": 17.79
        },
        {
          "projectId": 21042,
          "projectName": "The Purpose Of This Success Criterion Is",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "../../../assets/image/english-draft.png",
          "createDate": "2020-01-15T20:32:33.737",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "5a711c83",
          "mainVideoFileDuration": 16.73
        },
        {
          "projectId": 21032,
          "projectName": "Test Translate",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "../../../assets/image/english-draft.png",
          "createDate": "2020-01-14T02:03:16.737",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "821df0ba",
          "mainVideoFileDuration": 27.9
        },
        {
          "projectId": 21022,
          "projectName": "اختبار-017",
          "projectType": 2,
          "projectStatus": 2,
          "description": "",
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "../../../assets/image/english-draft.png",
          "createDate": "2020-01-13T18:12:04.433",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "4d780eb6",
          "mainVideoFileDuration": 38.769999999999996
        },
        {
          "projectId": 21017,
          "projectName": "اختبار-016",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "../../../assets/image/english-draft.png",
          "createDate": "2020-01-13T17:39:22.093",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "c024a5bb",
          "mainVideoFileDuration": 39.769999999999996
        },
        {
          "projectId": 21012,
          "projectName": "TEST",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "../../../assets/image/english-draft.png",
          "createDate": "2020-01-10T21:22:13.807",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "8060d53c",
          "mainVideoFileDuration": 39.769999999999996
        },
        {
          "projectId": 21011,
          "projectName": "ZXX",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "../../../assets/image/english-draft.png",
          "createDate": "2020-01-10T21:18:24.07",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "40ceaa07",
          "mainVideoFileDuration": 21.77
        },
        {
          "projectId": 20971,
          "projectName": "6G-H",
          "projectType": 2,
          "projectStatus": 2,
          "description": "",
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "../../../assets/image/english-draft.png",
          "createDate": "2020-01-03T23:29:08.127",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "b94dfa0b",
          "mainVideoFileDuration": 58.8
        }
      ],
      "videosLimit": null,
      "createdVideos": 64,
      "allowToCreateProject": true
    }
  

  constructor(private languageService: LanguageService) { }

  ngOnInit() {
  }

  changeLang(){
    this.languageService.changeLanguage(AppLanguages.ARABIC);
  }
}
