import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {

  powerPoints = 
    {
      "results": [
        {
          "projectId": 21041,
          "projectName": "The Persian Gulf Is A Mediterranean Sea",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "https://squigl.blob.core.windows.net/int/TruPort/Organizations/9130/Departments/9130/Projects/21041/Thumbs/ThePersianGulfIsAMediterraneanSea.jpeg?sv=2018-03-28&sr=b&sig=0qrnzKRgW0OnSf0F%2FKRDJcRa9DTzXf2c%2FoAIf4apC9I%3D&se=2020-01-19T19%3A36%3A45Z&sp=r",
          "createDate": "2020-01-15T18:10:48.96",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": true,
          "lockedTime": "2020-01-15T14:40:08.253",
          "lockedByEmail": "abe@abe.com",
          "lockedByPersonId": 9970,
          "viddlerVideoId": "cbe09119",
          "mainVideoFileDuration": 17.79
        },
        {
          "projectId": 21042,
          "projectName": "The Purpose Of This Success Criterion Is",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "https://squigl.blob.core.windows.net/int/TruPort/Organizations/9130/Departments/9130/Projects/21042/Thumbs/ThePurposeOfThisSuccessCriterionIs.jpeg?sv=2018-03-28&sr=b&sig=CTtqj99NJ%2BXk5wJ3t9VBwwSk91beFvDz1oH%2FncRTrzQ%3D&se=2020-01-19T19%3A36%3A45Z&sp=r",
          "createDate": "2020-01-15T20:32:33.737",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "5a711c83",
          "mainVideoFileDuration": 16.73
        },
        {
          "projectId": 21032,
          "projectName": "Test Translate",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "https://squigl.blob.core.windows.net/int/TruPort/Organizations/9130/Departments/9130/Projects/21032/Thumbs/TestTranslate.jpeg?sv=2018-03-28&sr=b&sig=nl43SExwO3l760m2qGD%2BsVWTDfFz7fMA8iybMk89fKw%3D&se=2020-01-19T19%3A36%3A45Z&sp=r",
          "createDate": "2020-01-14T02:03:16.737",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "821df0ba",
          "mainVideoFileDuration": 27.9
        },
        {
          "projectId": 21022,
          "projectName": "اختبار-017",
          "projectType": 2,
          "projectStatus": 2,
          "description": "",
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "https://squigl.blob.core.windows.net/int/TruPort/Organizations/9130/Departments/9130/Projects/21022/Thumbs/اختبار-018.jpeg?sv=2018-03-28&sr=b&sig=eztTIOekFZZ2VnxGB0oAI1qkkUHiiRt%2BXLqQe3bZKn8%3D&se=2020-01-19T19%3A36%3A45Z&sp=r",
          "createDate": "2020-01-13T18:12:04.433",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "4d780eb6",
          "mainVideoFileDuration": 38.769999999999996
        },
        {
          "projectId": 21017,
          "projectName": "اختبار-016",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "https://squigl.blob.core.windows.net/int/TruPort/Organizations/9130/Departments/9130/Projects/21017/Thumbs/اختبار.jpeg?sv=2018-03-28&sr=b&sig=5O%2FeWmD5lifML52TDwMR0RIfCQkt%2F9x%2FSp2lEcoma8I%3D&se=2020-01-19T19%3A36%3A45Z&sp=r",
          "createDate": "2020-01-13T17:39:22.093",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "c024a5bb",
          "mainVideoFileDuration": 39.769999999999996
        },
        {
          "projectId": 21012,
          "projectName": "TEST",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "https://squigl.blob.core.windows.net/int/TruPort/Organizations/9130/Departments/9130/Projects/21012/Thumbs/TEST-076.jpeg?sv=2018-03-28&sr=b&sig=BVGy5VfA873PlailGQxIfqsjEhVtDFDF3gpYsEqoy9w%3D&se=2020-01-19T19%3A36%3A45Z&sp=r",
          "createDate": "2020-01-10T21:22:13.807",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "8060d53c",
          "mainVideoFileDuration": 39.769999999999996
        },
        {
          "projectId": 21011,
          "projectName": "ZXX",
          "projectType": 2,
          "projectStatus": 2,
          "description": null,
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "https://squigl.blob.core.windows.net/int/TruPort/Organizations/9130/Departments/9130/Projects/21011/Thumbs/ZXX.jpeg?sv=2018-03-28&sr=b&sig=c6wEMN5SzTjPGLPCSfsrUZQHwePuKliDKiF0HMJjc%2FI%3D&se=2020-01-19T19%3A36%3A45Z&sp=r",
          "createDate": "2020-01-10T21:18:24.07",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "40ceaa07",
          "mainVideoFileDuration": 21.77
        },
        {
          "projectId": 20971,
          "projectName": "6G-H",
          "projectType": 2,
          "projectStatus": 2,
          "description": "",
          "departmentId": 9130,
          "organizationId": 9130,
          "totalFilesCount": 0,
          "mainVideoId": null,
          "mainVideoThumbnail": "https://squigl.blob.core.windows.net/int/TruPort/Organizations/9130/Departments/9130/Projects/20971/Thumbs/6G-H-002.jpeg?sv=2018-03-28&sr=b&sig=%2FM%2Be3jv4AqMHFX23%2Bvn6KISwvc7NoiaBQzR3N5x0sdc%3D&se=2020-01-19T19%3A36%3A45Z&sp=r",
          "createDate": "2020-01-03T23:29:08.127",
          "projectOwner": null,
          "timeline": null,
          "projectMembers": null,
          "deleted": false,
          "deletedDate": null,
          "category": null,
          "isLocked": false,
          "lockedTime": null,
          "lockedByEmail": null,
          "lockedByPersonId": null,
          "viddlerVideoId": "b94dfa0b",
          "mainVideoFileDuration": 58.8
        }
      ],
      "videosLimit": null,
      "createdVideos": 64,
      "allowToCreateProject": true
    }
  

  constructor() { }

  ngOnInit() {
  }

}
